//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BiblitekaEntities : DbContext
    {
        public BiblitekaEntities()
            : base("name=BiblitekaEntities")

        {

        }
        public static BiblitekaEntities GetContext()
        {
            if (_instance == null) _instance = new BiblitekaEntities();
            return _instance;
        }
        private static BiblitekaEntities _instance;
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<People> Peoples { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}